<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="MMA Plus Merchandising With Channel Wise Data Verification" time="7" tests="0" failures="2" errors="0">
   <testsuite name="MMA Plus Merchandising With Channel Wise Data Verification" tests="0" failures="2" errors="0" time="7" timestamp="2018-08-06 18:51:35" hostname="Fahad Shah - DESKTOP-L12UUAD" id="Test Suites/MMA Plus Merchandising With Channel Wise Data Verification">
      <properties>
         <property name="deviceName" value=""/>
         <property name="devicePlatform" value=""/>
         <property name="logFolder" value="F:\\Git Projects\\MMAPlus_Merchandising\\MMAPlus_Merchandising\\Reports\\MMA Plus Merchandising With Channel Wise Data Verification\\20180806_185133"/>
         <property name="logFiles" value="F:\\Git Projects\\MMAPlus_Merchandising\\MMAPlus_Merchandising\\Reports\\MMA Plus Merchandising With Channel Wise Data Verification\\20180806_185133\\appium.log, F:\\Git Projects\\MMAPlus_Merchandising\\MMAPlus_Merchandising\\Reports\\MMA Plus Merchandising With Channel Wise Data Verification\\20180806_185133\\execution0.log"/>
         <property name="attachments" value=""/>
         <property name="hostName" value="Fahad Shah - DESKTOP-L12UUAD"/>
         <property name="hostAddress" value="192.168.3.191"/>
         <property name="os" value="Windows 10 64bit"/>
         <property name="katalonVersion" value="5.6.0.1"/>
      </properties>
      <testcase name="Test Cases/LaunchingApp/LaunchApp" classname="Test Cases/LaunchingApp/LaunchApp" status="FAILED">
         <failure type="FAILED" message="Unable to start app at: 'F:\QA_Automation\Builds\mma_Merchandising_200618_local.apk' (Root cause: com.kms.katalon.core.appium.exception.AppiumStartException: Fail to start Appium server in 5 seconds)"/>
         <system-out><![CDATA[2018-08-06 18:51:36 - [TEST_CASE][FAILED] - Test Cases/LaunchingApp/LaunchApp: Test Cases/LaunchingApp/LaunchApp FAILED because (of) Unable to start app at: 'F:\QA_Automation\Builds\mma_Merchandising_200618_local.apk' (Root cause: com.kms.katalon.core.appium.exception.AppiumStartException: Fail to start Appium server in 5 seconds)

2018-08-06 18:51:36 - [TEST_STEP][FAILED] - startApplication: Unable to start app at: 'F:\QA_Automation\Builds\mma_Merchandising_200618_local.apk' (Root cause: com.kms.katalon.core.appium.exception.AppiumStartException: Fail to start Appium server in 5 seconds)

2018-08-06 18:51:42 - [MESSAGE][FAILED] - Unable to start app at: 'F:\QA_Automation\Builds\mma_Merchandising_200618_local.apk' (Root cause: com.kms.katalon.core.appium.exception.AppiumStartException: Fail to start Appium server in 5 seconds)]]></system-out>
         <system-err><![CDATA[2018-08-06 18:51:36 - [TEST_CASE][FAILED] - Test Cases/LaunchingApp/LaunchApp: Test Cases/LaunchingApp/LaunchApp FAILED because (of) Unable to start app at: 'F:\QA_Automation\Builds\mma_Merchandising_200618_local.apk' (Root cause: com.kms.katalon.core.appium.exception.AppiumStartException: Fail to start Appium server in 5 seconds)]]></system-err>
      </testcase>
      <testcase name="Test Cases/VisitShopScenarios/VisitShopsWithDataVerification" classname="Test Cases/VisitShopScenarios/VisitShopsWithDataVerification" status="FAILED">
         <failure type="FAILED" message="No driver found"/>
         <system-out><![CDATA[2018-08-06 18:51:42 - [TEST_CASE][FAILED] - Test Cases/VisitShopScenarios/VisitShopsWithDataVerification: Test Cases/VisitShopScenarios/VisitShopsWithDataVerification FAILED because (of) No driver found

2018-08-06 18:51:42 - [TEST_STEP][PASSED] - verifyElementText: Checking timeout]]></system-out>
         <system-err><![CDATA[2018-08-06 18:51:42 - [TEST_CASE][FAILED] - Test Cases/VisitShopScenarios/VisitShopsWithDataVerification: Test Cases/VisitShopScenarios/VisitShopsWithDataVerification FAILED because (of) No driver found]]></system-err>
      </testcase>
      <system-out><![CDATA[2018-08-06 18:51:35 - [TEST_SUITE][FAILED] - MMA Plus Merchandising With Channel Wise Data Verification: Test Cases/LaunchingApp/LaunchApp FAILED because (of) Unable to start app at: 'F:\QA_Automation\Builds\mma_Merchandising_200618_local.apk' (Root cause: com.kms.katalon.core.appium.exception.AppiumStartException: Fail to start Appium server in 5 seconds)]]></system-out>
      <system-err><![CDATA[2018-08-06 18:51:35 - [TEST_SUITE][FAILED] - MMA Plus Merchandising With Channel Wise Data Verification: Test Cases/LaunchingApp/LaunchApp FAILED because (of) Unable to start app at: 'F:\QA_Automation\Builds\mma_Merchandising_200618_local.apk' (Root cause: com.kms.katalon.core.appium.exception.AppiumStartException: Fail to start Appium server in 5 seconds)]]></system-err>
   </testsuite>
</testsuites>
